AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
  Max: 35

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "bin/**/*"
    - "Gemfile"
    - "Rakefile"

Style/StringLiterals:
  EnforcedStyle: double_quotes
